### ISSUE TITLE
v2.2.1 python error

### ISSUE THREAD

**Issue by Nekololizu** [tanjeffreyz/auto-maple#77]
python setup.py still works fine if I use it for 2.1.2, not sure if something is wrong with the new files or just my python files ?

```
C:\auto-maple-2.2.1>python setup.py
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\git\__init__.py", line 87, in <module>
    refresh()
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\git\cmd.py", line 341, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\auto-maple-2.2.1\setup.py", line 4, in <module>
    import git
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\git\__init__.py", line 89, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

**Comment by tanjeffreyz** [comment]
Hi, really sorry about that! I forgot to add downloading Git to the [setup instructions](https://github.com/tanjeffreyz/auto-maple#--setup), please let me know if this fixes it.

**Comment by Nekololizu** [comment]
> Hi, really sorry about that! I forgot to add downloading Git (step 3) to the [setup instructions](https://github.com/tanjeffreyz/auto-maple#--setup), please let me know if this fixes it.

It made a shortcut now at least, but threw out a few more errors
Did everything default during the install
```
C:\auto-maple-2.2.1>python setup.py

[~] Creating a desktop shortcut for Auto Maple:
 -  Enabled the "Run as Administrator" option
 ~  Successfully created Auto Maple shortcut

[~] Updating submodules:
Traceback (most recent call last):
  File "C:\auto-maple-2.2.1\setup.py", line 60, in <module>
    update_submodules()
  File "C:\auto-maple-2.2.1\setup.py", line 41, in update_submodules
    repo = git.Repo()
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\git\repo\base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\git\repo\base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
```

**Comment by Nekololizu** [comment]
Works fine now 👌
