### ISSUE TITLE
Shortcut Error

### ISSUE THREAD

**Issue by Nekololizu** [tanjeffreyz/auto-maple#87]
```
C:\auto-maple>python setup.py

[~] Creating desktop shortcut for Auto Maple:
Traceback (most recent call last):
  File "C:\auto-maple\setup.py", line 43, in <module>
    create_desktop_shortcut()
  File "C:\auto-maple\setup.py", line 24, in create_desktop_shortcut
    shortcut.save()
  File "<COMObject <unknown>>", line 2, in save
pywintypes.com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, 'WshShortcut.Save', 'Die Verknüpfung "C:\Users\Gangs\Desktop\Auto Maple.lnk" wurde nicht gespeichert.', None, 0, -2147024893), None)
```

**Comment by ScottBouloutian** [comment]
I've never used the shortcut, typically just run `python main.py`

**Comment by nehcap** [comment]
> 

hey can i have you discord?

**Comment by Nekololizu** [comment]
> 

I tried to set it up for a friend over teamviewer and haven't had this error myself, Guess il just make a bat file with "python main.py" and see if that could be a good workaround as a budget shortcut

**Comment by tanjeffreyz** [comment]
Hi, this should be fixed in the [newest release](https://github.com/tanjeffreyz/auto-maple/releases/tag/v2.3.3)
