### ISSUE TITLE
Disable Record Position when no book is loaded

### ISSUE THREAD

**Issue by Nekololizu** [tanjeffreyz/auto-maple#89]
**Issue:** Recording positions and trying to make a routine before loading a book stops you from saving a csv file with the error below and if you load a book it will wipe the current routine due to force unloading it when loading a book

**Solution:** Recording positions/routine editing should be disabled before a command book is loaded to avoid losing routine editing progress

```
##################
#    ENABLED     #
##################

[~] Recorded position (0.431, 0.182) at 10:36:22 PM

[!] 'Buff' command not implemented in current command book, aborting process.
Exception in thread Thread-19:
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\auto-maple\src\common\utils.py", line 238, in run
    self.function(*self.args, **self.kwargs)
  File "C:\auto-maple\src\common\utils.py", line 35, in helper
    return function(*args, **kwargs)
  File "C:\auto-maple\src\gui\menu\file.py", line 41, in _save_routine
    file_path = asksaveasfilename(initialdir=get_routines_dir(),
  File "C:\auto-maple\src\gui\menu\file.py", line 80, in get_routines_dir
    target = os.path.join(config.RESOURCES_DIR, 'routines', config.bot.module_name)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

**Comment by tanjeffreyz** [comment]
Thanks for the heads up, the fix will be in the next patch, hopefully along with reloading command book changes without restarting the program!

**Comment by Nekololizu** [comment]
> Thanks for the heads up, the fix will be in the next patch, hopefully along with reloading command book changes without restarting the program!

No worries, think this was the error I had when trying to test the adele book without me really realizing it
